#####################################################################################################################
# Documentation: https://bitbucket.org/zepben/how-tos/src/master/bitbucket_pipelines/release-management.md
# Custom Images used: https://bitbucket.org/zepben/vm-container-images/
#####################################################################################################################
image: zepben/pipeline-java

options:
  max-time: 30

definitions:
  zep-basic-image: &zep-basic-image
    image: zepben/pipeline-basic:2.0.0

  steps:
    - step: &build-test-step
        name: Build and Test
        caches:
          - maven
        script:
          - mvn clean test -f pom.xml -Dserver.username=$NEXUS_USERNAME -Dserver.password=$NEXUS_PASSWORD -Dserver.repo.url=$NEXUS_MAVEN_REPO 
    - step: &release-step
        name: Package and Upload artifact
        caches:
          - maven
        script:
          - mvn clean deploy -f pom.xml -Dserver.username=$NEXUS_USERNAME -Dserver.password=$NEXUS_PASSWORD -Dserver.repo.url=$NEXUS_MAVEN_REPO -Dserver.release.url=$NEXUS_MAVEN_RELEASE -Dserver.snapshot.url=$NEXUS_MAVEN_SNAPSHOT 
          - export artifact=$(ls target/ | grep -o "^.*[0-9]\+\.[0-9]\+\.[0-9]\+\(\-SNAPSHOT\)\?\.jar")
          - pipe: atlassian/slack-notify:0.3.6
            variables:
              WEBHOOK_URL: $SLACK_WEBHOOK
              MESSAGE: "$artifact is available."

pipelines:
  branches:
    master: 
      - step: *release-step
    LTS/*:
      - step: *release-step
    hotfix/*:
      - step: *release-step
  pull-requests:
    '**': 
      - step: *build-test-step

  tags:
    '*.*.*':
      - step: *release-step

  custom:
    create-release:
      - step:
          name: Create release
          <<: *zep-basic-image
          script:
            - release-checks
            - java-mvn-finalize-version pom.xml
            - java-mvn-update-version pom.xml
            - rebase

    create-LTS-branch:
      - step:
          <<: *zep-basic-image
          name: Create LTS branch
          script:
            - create-branch --lts
            - export BITBUCKET_BRANCH=$(git rev-parse --abbrev-ref HEAD)
            - java-mvn-update-version pom.xml

    create-hotfix-branch:
      - step:
          <<: *zep-basic-image
          name: Create Hotfix branch
          script:
            - create-branch --hotfix
            - export BITBUCKET_BRANCH=$(git rev-parse --abbrev-ref HEAD)
            - java-mvn-update-version pom.xml